# Generated by Django 2.2.7 on 2020-05-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_type', models.CharField(choices=[('value', '上下限值'), ('percent', '上下限百分比')], max_length=32, verbose_name='监控类型')),
                ('server_add', models.CharField(blank=True, choices=[('10.130.146.11', '报表平台 (10.130.146.11)'), ('10.130.146.13', '决策系统 (10.130.146.13)'), ('10.126.75.56', '虚拟机 (10.126.75.56)')], max_length=128, null=True, verbose_name='数据服务器')),
                ('t_name', models.CharField(max_length=128, verbose_name='监控表名称')),
                ('c_name', models.CharField(max_length=128, verbose_name='监控字段名称')),
                ('condition', models.CharField(blank=True, max_length=256, null=True, verbose_name='监控条件')),
                ('time_option', models.CharField(blank=True, choices=[(None, '------'), ('today', '今天(yyyy-mm-dd)'), ('yesterday', '昨天(yyyy-mm-dd)'), ('now_year', '当年(yyyy)'), ('now_month', '当月(yyyy-mm)'), ('now_month_only', '当月(mm)'), ('last_month', '上月(yyyy-mm)'), ('last_month_only', '上月(mm)'), ('the_month_before_last', '上上月(yyyy-mm)'), ('the_month_before_last_only', '上上月(mm)')], default=None, max_length=128, null=True, verbose_name='监控条件时间选择')),
                ('cpr_time_option', models.CharField(blank=True, choices=[(None, '------'), ('today', '今天(yyyy-mm-dd)'), ('yesterday', '昨天(yyyy-mm-dd)'), ('now_year', '当年(yyyy)'), ('now_month', '当月(yyyy-mm)'), ('now_month_only', '当月(mm)'), ('last_month', '上月(yyyy-mm)'), ('last_month_only', '上月(mm)'), ('the_month_before_last', '上上月(yyyy-mm)'), ('the_month_before_last_only', '上上月(mm)')], default=None, max_length=128, null=True, verbose_name='对比条件时间选择')),
                ('up_value', models.FloatField(max_length=128, verbose_name='监控上限值、百分比')),
                ('down_value', models.FloatField(max_length=128, verbose_name='监控下限值、百分比')),
                ('r_time', models.TimeField(verbose_name='执行时间')),
                ('o_user_email', models.EmailField(max_length=128, verbose_name='创建人邮箱')),
                ('p_user_email', models.EmailField(max_length=128, verbose_name='推送人邮箱')),
                ('notes', models.CharField(max_length=128, verbose_name='备注')),
                ('t_state', models.CharField(choices=[('1', '上线'), ('0', '下线')], default='1', max_length=128, verbose_name='任务状态')),
                ('c_state', models.CharField(blank=True, default='准备', max_length=32, null=True, verbose_name='监控状态')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '阈值监控',
                'ordering': ['-c_time'],
                'verbose_name_plural': '阈值监控',
            },
        ),
    ]
