# Generated by Django 2.2.7 on 2019-12-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_type', models.CharField(choices=[('equal_zero', '为0'), ('equal_null', '为空'), ('equal_neg', '为负'), ('delay', '数据延迟')], max_length=32, verbose_name='监控类型')),
                ('s_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='调度id')),
                ('server_add', models.CharField(blank=True, choices=[('10.130.146.11', '报表平台 (10.130.146.11)'), ('10.130.146.13', '决策系统 (10.130.146.13)'), ('10.126.75.56', '虚拟机 (10.126.75.56)')], max_length=128, null=True, verbose_name='数据服务器')),
                ('t_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='监控表名称')),
                ('c_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='监控字段名称')),
                ('condition', models.CharField(blank=True, max_length=256, null=True, verbose_name='监控条件')),
                ('time_option', models.CharField(blank=True, choices=[('today', '今天(yyyy-mm-dd)'), ('yesterday', '昨天(yyyy-mm-dd)'), ('now_year', '当年(yyyy)'), ('now_month', '当月(yyyy-mm)'), ('now_month_only', '当月(mm)'), ('last_month', '上月(yyyy-mm)'), ('last_month_only', '上月(mm)')], max_length=128, null=True, verbose_name='条件时间选择')),
                ('r_time', models.TimeField(verbose_name='执行时间')),
                ('o_user_email', models.EmailField(max_length=128, verbose_name='创建人邮箱')),
                ('p_user_email', models.EmailField(max_length=128, verbose_name='推送人邮箱')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '异常监控',
                'verbose_name': '异常监控',
                'ordering': ['-c_time'],
            },
        ),
    ]
