# Generated by Django 2.2.7 on 2019-12-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_ctrl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error_task',
            name='c_name',
            field=models.CharField(max_length=128, verbose_name='监控字段名称'),
        ),
        migrations.AlterField(
            model_name='error_task',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='error_task',
            name='c_type',
            field=models.CharField(choices=[('equal_zero', '为0'), ('equal_null', '为空'), ('equal_neg', '为负'), ('delay', '数据延迟')], max_length=32, verbose_name='监控类型'),
        ),
        migrations.AlterField(
            model_name='error_task',
            name='o_user_email',
            field=models.EmailField(max_length=128, verbose_name='创建人邮箱'),
        ),
        migrations.AlterField(
            model_name='error_task',
            name='p_user_email',
            field=models.EmailField(max_length=128, verbose_name='推送人邮箱'),
        ),
        migrations.AlterField(
            model_name='error_task',
            name='r_time',
            field=models.TimeField(verbose_name='执行时间'),
        ),
        migrations.AlterField(
            model_name='error_task',
            name='s_id',
            field=models.CharField(max_length=32, verbose_name='调度id'),
        ),
        migrations.AlterField(
            model_name='error_task',
            name='t_name',
            field=models.CharField(max_length=128, verbose_name='监控表名称'),
        ),
        migrations.AlterField(
            model_name='error_task',
            name='u_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
