# Generated by Django 2.2.7 on 2019-12-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_ctrl', '0003_auto_20191218_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error_task',
            name='c_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='监控字段名称'),
        ),
        migrations.AlterField(
            model_name='error_task',
            name='s_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='调度id'),
        ),
        migrations.AlterField(
            model_name='error_task',
            name='t_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='监控表名称'),
        ),
    ]
