# Generated by Django 2.2.7 on 2019-12-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_ctrl', '0004_auto_20191218_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='error_task',
            name='condition',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='监控条件'),
        ),
        migrations.AddField(
            model_name='error_task',
            name='time_option',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='时间选择'),
        ),
    ]
