# Generated by Django 2.2.7 on 2019-12-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_ctrl', '0005_auto_20191225_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error_task',
            name='time_option',
            field=models.CharField(blank=True, choices=[('today', '今天(yyyy-mm-dd)'), ('yesterday', '昨天(yyyy-mm-dd)'), ('now_year', '当年(yyyy)'), ('now_month', '当月(yyyy-mm)'), ('now_month_only', '当月(mm)'), ('last_month', '上月(yyyy-mm)'), ('last_month_only', '上月(mm)')], default=None, max_length=128, null=True, verbose_name='时间选择'),
        ),
    ]
