# Generated by Django 2.2.7 on 2019-12-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('phone', models.CharField(max_length=32, unique=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('u_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '用户',
                'ordering': ['-c_time'],
                'verbose_name': '用户',
            },
        ),
    ]
